### ISSUE TITLE
Feature request: Support setting --preserve-order option for sjsonnet

### ISSUE THREAD

**Issue by dpjmn** [chklauser/sjsonnet-gradle-plugin#2]
I have some json configs where the the keys are ordered logically instead of alphabetically to make them easier for humans to read.
sjsonnet has a --preserve-order setting, which keeps the input order.

It would be very nice to be able to set this option through the gradle plugin.

**Comment by chklauser** [comment]
Hey @dpjmn,

Thanks for taking the time to type up the feature request. Passing these flag-style settings through to Sjsonnet was pretty easy.

As I kind of left the Java world behind some years ago, I don't have access to any "industrial-grade" projects that use `sjsonnet-gradle-plugin` 😉 Could I ask you to test the new version [1.1.0-rc.1](https://plugins.gradle.org/plugin/io.github.chklauser.sjsonnet/1.1.0-rc.1) for me in your project?

If all works well, I'll publish the final 1.1.0 version.

**Comment by dpjmn** [comment]
I just tested 1.1.0-rc.1 in my project, and it works great.

Thank you very much for taking the time to implement this!

**Comment by chklauser** [comment]
You're welcome!

[1.1.0](https://plugins.gradle.org/plugin/io.github.chklauser.sjsonnet) released
